group=me.a1i
version=0.1.0
pluginRepositoryUrl=https://github.com/ali-v-1985/contextual-bookmarks-plugin

kotlin.stdlib.default.dependency=false
org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true
org.jetbrains.intellij.platform.selfUpdateCheck=false
org.jetbrains.intellij.platform.verifyPluginDefaultRecommendedIdes=false
org.jetbrains.intellij.platform.verifyPluginProjectConfigurationMutedMessages=until-build property should be removed
